use_frameworks!

platform :ios, '10.0'

target 'HRViewVisible_Example' do
  pod 'HRViewVisible', :path => '../'

  target 'HRViewVisible_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
